#docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db

#docker-compose run --rm app sh -c "python manage.py test"

version: '3.9'

services:
  db:
    image: postgres:14-alpine
    privileged: true
    container_name: db
    restart: always
    ports:
      - "54325:5432"
    environment:
      POSTGRES_DB: blackemployer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static:/vol/web/static
      - ./app:/app
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic
      && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: 'app.settings.prod_postgres'
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static:/static


volumes:
  static:
  db:
