FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

COPY  blackemployer.crt /etc/ssl/blackemployer.crt
COPY  blackemployer.key /etc/ssl/blackemployer.key
COPY  ca.crt /etc/ssl/ca.crt
