# Generated by Django 4.0.3 on 2022-03-18 09:23

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, max_length=400, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO keywords')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case_date', models.DateTimeField(blank=True, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=256, null=True)),
                ('position_description', models.TextField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=utils.model_utils.PathAndRename('images/cases/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]), blank=True, default=utils.model_utils.default_1d_array, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), default=utils.model_utils.default_1d_array_of_strings, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), default=utils.model_utils.default_1d_array_of_strings, size=None)),
                ('telegram', models.CharField(blank=True, max_length=128, null=True)),
                ('skype', models.CharField(blank=True, max_length=128, null=True)),
                ('slack', models.CharField(blank=True, max_length=128, null=True)),
                ('other', models.CharField(blank=True, max_length=128, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, max_length=400, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO keywords')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=utils.model_utils.PathAndRename('images/companies/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])])),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, max_length=400, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO keywords')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=utils.model_utils.PathAndRename('images/comments/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]), blank=True, default=utils.model_utils.default_1d_array, null=True, size=None)),
                ('case', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.case')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='comment_likes', to='content.like')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.ManyToManyField(related_name='case_contacts', to='companies.contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(related_name='case_tags', to='content.tag'),
        ),
    ]
