# Generated by Django 4.0.3 on 2022-03-15 14:39

import companies.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=companies.models.PathAndRename('images/cases/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]), blank=True, default=companies.models.default_1d_array, null=True, size=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=companies.models.PathAndRename('images/comments/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]), blank=True, default=companies.models.default_1d_array, null=True, size=None),
        ),
    ]
