# Generated by Django 4.0.3 on 2022-03-16 09:46

import companies.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_case_images_comment_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date',
            new_name='case_date',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='text',
            new_name='case_description',
        ),
        migrations.AddField(
            model_name='case',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='position_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), default=companies.models.default_1d_array_of_strings, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), default=companies.models.default_1d_array_of_strings, size=None)),
                ('telegram', models.CharField(blank=True, max_length=128, null=True)),
                ('skype', models.CharField(blank=True, max_length=128, null=True)),
                ('slack', models.CharField(blank=True, max_length=128, null=True)),
                ('other', models.CharField(blank=True, max_length=128, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.ManyToManyField(related_name='case_contacts', to='companies.contact'),
        ),
    ]
