# Generated by Django 4.0.3 on 2022-03-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_date_case_case_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='company',
        ),
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.case'),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
